"""Scanner support-matrix primitives.

This package is intentionally additive. It defines scanner contracts and registry
metadata before runtime ingestion paths are moved onto the scanner substrate.
"""

from QueryLake.scanning.contracts import (
    AcquisitionMode,
    ArtifactRef,
    GeometryLevel,
    PageRecord,
    Projection,
    ProjectionKind,
    RoutingDecision,
    ScanContract,
    ScanObject,
    ScanRequest,
    ScanRun,
    ScannerEnvelope,
    StructureLevel,
    SupportTier,
    materialize_legacy_markdown_envelope,
    normalize_legacy_output_contract,
)
from QueryLake.scanning.adapters import (
    AdapterAvailability,
    LegacyMarkdownScanResult,
    ScannerAdapter,
    ScannerRunContext,
)
from QueryLake.scanning.availability import scanner_availability_rows, scanner_availability_to_markdown
from QueryLake.scanning.chandra import ChandraCompatibilityAdapter, build_chandra_compatibility_envelope
from QueryLake.scanning.docling import DoclingLocalParserAdapter
from QueryLake.scanning.integration import (
    build_scanner_document_artifact_payload,
    build_scanner_enriched_ocr_done_payload,
    build_scanner_job_result_metadata,
)
from QueryLake.scanning.evaluation import (
    ScannerPromotionDecision,
    ScannerPromotionThresholds,
    ScannerEvalCase,
    ScannerEvalResult,
    decide_backend_promotion,
    eval_results_to_markdown,
    evaluate_scanner_envelope_contract,
    load_eval_manifest,
    promotion_decisions_to_markdown,
    summarize_eval_results,
    validate_eval_cases,
)
from QueryLake.scanning.eval_diff import (
    ScannerEvalDiff,
    diff_eval_results,
    eval_diff_to_markdown,
    load_eval_results,
)
from QueryLake.scanning.eval_runner import mock_envelope_for_eval_case, run_mock_eval
from QueryLake.scanning.native import (
    NativeExtractionResult,
    NativeTextQualityAssessment,
    NativeTextQualityError,
    NativeTextQualityPolicy,
    PyMuPDF4LLMNativeAdapter,
    assess_native_text_quality,
    split_markdown_pages,
)
from QueryLake.scanning.persistence import (
    SCANNER_ARTIFACT_TYPES,
    SCANNER_CANONICAL_MARKDOWN_ARTIFACT_TYPE,
    SCANNER_CANONICAL_TEXT_ARTIFACT_TYPE,
    SCANNER_ENVELOPE_ARTIFACT_TYPE,
    SCANNER_LAYOUT_GRAPH_ARTIFACT_TYPE,
    SCANNER_RAW_PAYLOAD_ARTIFACT_TYPE,
    SCANNER_SHADOW_RESULT_ARTIFACT_TYPE,
    SCANNER_STRUCTURED_FIELDS_ARTIFACT_TYPE,
    PersistedScannerEnvelope,
    read_scanner_envelope_payload,
    scanner_envelope_to_json_bytes,
    summarize_scanner_envelope_payload,
    write_scanner_envelope,
)
from QueryLake.scanning.providers import (
    GeminiDocumentFallbackMockAdapter,
    MistralOCRMockAdapter,
    ProviderMockResult,
    ProviderPolicy,
    ProviderPolicyError,
)
from QueryLake.scanning.shadow import MinerUShadowAdapter, ShadowParserResult
from QueryLake.scanning.registry import (
    ScannerBackendSpec,
    build_default_scanner_registry,
    get_backend_spec,
    registry_report_rows,
    validate_backend_spec,
    validate_scanner_registry,
)
from QueryLake.scanning.routing import (
    RoutingPlan,
    RoutingPolicy,
    explain_routing_plan,
    plan_scan_route,
    policy_from_request,
    routing_plan_to_markdown,
)

__all__ = [
    "AcquisitionMode",
    "AdapterAvailability",
    "ArtifactRef",
    "ChandraCompatibilityAdapter",
    "DoclingLocalParserAdapter",
    "GeminiDocumentFallbackMockAdapter",
    "GeometryLevel",
    "LegacyMarkdownScanResult",
    "PageRecord",
    "Projection",
    "ProjectionKind",
    "RoutingDecision",
    "ScanContract",
    "ScanObject",
    "ScanRequest",
    "ScanRun",
    "ScannerBackendSpec",
    "ScannerEvalDiff",
    "ScannerEvalCase",
    "ScannerEvalResult",
    "ScannerPromotionDecision",
    "ScannerPromotionThresholds",
    "ScannerAdapter",
    "ScannerEnvelope",
    "ScannerRunContext",
    "ShadowParserResult",
    "StructureLevel",
    "SupportTier",
    "RoutingPlan",
    "RoutingPolicy",
    "PersistedScannerEnvelope",
    "NativeExtractionResult",
    "NativeTextQualityAssessment",
    "NativeTextQualityError",
    "NativeTextQualityPolicy",
    "MistralOCRMockAdapter",
    "MinerUShadowAdapter",
    "PyMuPDF4LLMNativeAdapter",
    "ProviderMockResult",
    "ProviderPolicy",
    "ProviderPolicyError",
    "SCANNER_ARTIFACT_TYPES",
    "SCANNER_CANONICAL_MARKDOWN_ARTIFACT_TYPE",
    "SCANNER_CANONICAL_TEXT_ARTIFACT_TYPE",
    "SCANNER_ENVELOPE_ARTIFACT_TYPE",
    "SCANNER_LAYOUT_GRAPH_ARTIFACT_TYPE",
    "SCANNER_RAW_PAYLOAD_ARTIFACT_TYPE",
    "SCANNER_SHADOW_RESULT_ARTIFACT_TYPE",
    "SCANNER_STRUCTURED_FIELDS_ARTIFACT_TYPE",
    "build_default_scanner_registry",
    "build_chandra_compatibility_envelope",
    "build_scanner_document_artifact_payload",
    "build_scanner_enriched_ocr_done_payload",
    "build_scanner_job_result_metadata",
    "assess_native_text_quality",
    "decide_backend_promotion",
    "diff_eval_results",
    "eval_diff_to_markdown",
    "eval_results_to_markdown",
    "evaluate_scanner_envelope_contract",
    "explain_routing_plan",
    "get_backend_spec",
    "load_eval_manifest",
    "load_eval_results",
    "materialize_legacy_markdown_envelope",
    "mock_envelope_for_eval_case",
    "normalize_legacy_output_contract",
    "registry_report_rows",
    "validate_backend_spec",
    "plan_scan_route",
    "policy_from_request",
    "promotion_decisions_to_markdown",
    "read_scanner_envelope_payload",
    "routing_plan_to_markdown",
    "run_mock_eval",
    "scanner_availability_rows",
    "scanner_availability_to_markdown",
    "scanner_envelope_to_json_bytes",
    "summarize_scanner_envelope_payload",
    "summarize_eval_results",
    "split_markdown_pages",
    "validate_scanner_registry",
    "validate_eval_cases",
    "write_scanner_envelope",
]
