const globalStyleSettings = {
    normalTextFont: "Inter-Regular",
    boldTextFont: "Inter-Bold",
    codeTextFont: "Consolas",
    textSizeScale: 1,
    color1: "#23232D",
    color2: "#17181D",
    color3: "#E8E3E3",
    color4: "#88C285",
    color5: "#FED47D",
    color6: "#FFAAC7",
    color7: "#7968D9",
    color8: "#4D4D56",
    color9: "#1F1F28",
    color10: "#74748B",
    color11: "#39393C",
    colorText: "#E8E3E3",
    colorTextContrastive: "#1F1F28",
    collectionSelectCircleEmptyColor: "#7968D9",
    collectionSelectCircleFillColor: "#23232D",
    collectionWrapperBackgroundColor: "#39393C",
    collectionPreviewBackgroundColor: "#23232D",
    collectionPreviewCountTextColor: "#23232D",
    collectionPreviewCountBubbleColor: "#D9D9D9",
    loginTitleFont: "Inter-Regular",
    loginEntryFont: "Inter-Regular",
    chatRegularFont: "Inter-Regular",
    chatBoldFont: "Inter-Bold",
    chatCodeFont: "Consolas",
    chatDefaultFontSize: 14,

}

export default globalStyleSettings;