// This file is autogenerated by lib/build-toolchain-components.js
import type { ToolchainComponentManifest } from "@/types/toolchain-component-manifest";

export const TOOLCHAIN_V2_MANIFESTS: ToolchainComponentManifest[] = [
  {
    "id": "audio-recorder",
    "kind": "display",
    "title": "Test Component",
    "category": "Text Display",
    "description": "This is a test component."
  },
  {
    "id": "basf-intro-screen",
    "kind": "input",
    "title": "BASF Intro Screen",
    "category": "Text",
    "description": "A Preview for chat intro.",
    "hooks": {
      "on_upload": {
        "label": "on_upload"
      },
      "on_submit": {
        "label": "on_submit"
      },
      "selected_collections": {
        "label": "selected_collections"
      },
      "submit": {
        "label": "Submit"
      }
    },
    "config": {
      "test_7_long_string": {
        "type": "string",
        "default": "Hello, how are you?",
        "multiline": true
      }
    },
    "bindings": {
      "chatHistory": {
        "label": "Chat history",
        "kind": "state"
      }
    }
  },
  {
    "id": "chat-input",
    "kind": "input",
    "title": "Chat Input",
    "category": "Text",
    "description": "A chat input component that optionally supports file uploads.",
    "hooks": {
      "on_upload": {
        "label": "on_upload"
      },
      "on_submit": {
        "label": "on_submit"
      },
      "selected_collections": {
        "label": "selected_collections"
      },
      "submit": {
        "label": "Submit"
      },
      "openCollections": {
        "label": "Open collections"
      },
      "openModel": {
        "label": "Open model picker"
      }
    },
    "config": {
      "allowUploads": {
        "type": "boolean",
        "default": true
      },
      "multiple": {
        "type": "boolean",
        "default": true
      },
      "showCollections": {
        "type": "boolean",
        "default": false
      },
      "showModelPicker": {
        "type": "boolean",
        "default": false
      }
    }
  },
  {
    "id": "chat-with-rating",
    "kind": "input",
    "title": "File Upload",
    "category": "Input",
    "description": "A dropzone box for file uploads that immediately triggers on upload.",
    "hooks": {
      "on_rating": {
        "label": "on_rating"
      }
    },
    "config": {
      "Type": {
        "type": "string",
        "default": "Boolean",
        "multiline": true
      },
      "Label": {
        "type": "string",
        "default": "Rate this response"
      }
    }
  },
  {
    "id": "chat",
    "kind": "display",
    "title": "Chat",
    "category": "Text Display",
    "description": "A user and assistant chat display component that renders markdown, similar to OpenAI's ChatGPT.",
    "bindings": {
      "messages": {
        "label": "Chat history",
        "kind": "state"
      }
    }
  },
  {
    "id": "current-event-display",
    "kind": "display",
    "title": "Active Node Indicator",
    "category": "Debugging",
    "description": "Displays the current active node in the toolchain while running."
  },
  {
    "id": "file-upload",
    "kind": "input",
    "title": "File Upload",
    "category": "Input",
    "description": "A dropzone box for file uploads that immediately triggers on upload.",
    "hooks": {
      "on_upload": {
        "label": "on_upload"
      },
      "selected_collections": {
        "label": "selected_collections"
      }
    },
    "config": {
      "multiple": {
        "type": "boolean",
        "default": false
      }
    }
  },
  {
    "id": "markdown",
    "kind": "display",
    "title": "Markdown",
    "category": "Text Display",
    "description": "Displays text as markdown."
  },
  {
    "id": "switch",
    "kind": "input",
    "title": "Switch",
    "category": "ShadCN Components",
    "description": "A simple toggle switch.",
    "hooks": {
      "value_map": {
        "label": "value_map"
      }
    },
    "config": {
      "Label": {
        "type": "string",
        "default": ""
      }
    }
  },
  {
    "id": "text",
    "kind": "display",
    "title": "Text",
    "category": "Text Display",
    "description": "Displays text as-is, without rendering it as markdown or processing it in any way."
  }
];

export const TOOLCHAIN_V2_LOADERS: Record<string, () => Promise<{ default: any }>> = {
  "audio-recorder": () => import("@/toolchain_components/audio-recorder"),
  "basf-intro-screen": () => import("@/toolchain_components/basf-intro-screen"),
  "chat-input": () => import("@/toolchain_components/chat-input"),
  "chat-with-rating": () => import("@/toolchain_components/chat-with-rating"),
  "chat": () => import("@/toolchain_components/chat"),
  "current-event-display": () => import("@/toolchain_components/current-event-display"),
  "file-upload": () => import("@/toolchain_components/file-upload"),
  "markdown": () => import("@/toolchain_components/markdown"),
  "switch": () => import("@/toolchain_components/switch"),
  "text": () => import("@/toolchain_components/text")
};
