const fs = require("fs");
const path = require("path");

const SOURCE_DIRECTORY = "lib/themes";
const CACHE_DIRECTORY = "public/cache/themes";
const OUTPUT_FILE = "all_themes.tsx";

const toExportKey = (fileName) =>
  path.basename(fileName, ".json").replace(/[^a-zA-Z0-9_]/g, "_");

const readThemes = () => {
  if (!fs.existsSync(SOURCE_DIRECTORY)) {
    throw new Error(`Theme source directory does not exist: ${SOURCE_DIRECTORY}`);
  }

  const themeFiles = fs
    .readdirSync(SOURCE_DIRECTORY)
    .filter((fileName) => path.extname(fileName) === ".json")
    .sort();

  if (themeFiles.length === 0) {
    throw new Error(`No theme JSON files found in ${SOURCE_DIRECTORY}`);
  }

  return Object.fromEntries(
    themeFiles.map((fileName) => {
      const filePath = path.join(SOURCE_DIRECTORY, fileName);
      const rawTheme = fs.readFileSync(filePath, "utf8");

      return [toExportKey(fileName), JSON.parse(rawTheme)];
    })
  );
};

const themes = readThemes();

fs.mkdirSync(CACHE_DIRECTORY, { recursive: true });

const output = `// This file is autogenerated by lib/build-themes.js.
// Do not edit this file directly.

export const SYSTEM_THEMES = ${JSON.stringify(themes, null, 2)} as const;

export default SYSTEM_THEMES;
`;

fs.writeFileSync(path.join(CACHE_DIRECTORY, OUTPUT_FILE), output);

console.log(`Themes cached: ${Object.keys(themes).join(", ")}`);
